export interface Treatment {
  name: string;
  shortName: string;
}

export const WELLNESS_TREATMENTS: Treatment[] = [
  { name: "OZON: Bath", shortName: "OZ-BATH" },
  { name: "Acupressure_IPD", shortName: "ACU" },
  { name: "ACUPUNCTURE", shortName: "ACUPUNCTURE" },
  { name: "Aalovera Gel + Coconut oil + Karpura Massage", shortName: "Anti-Allergic-FBM" },
  { name: "ALOVERA FACE PACK", shortName: "ALOVERA F PK" },
  { name: "ALOVERA GHRIH KULLA", shortName: "ALOVERA GHRIH KULLA" },
  { name: "ANTI AGING FACE PACK", shortName: "ANTI AGE FP" },
  { name: "Anti Allergic Lepa", shortName: "AAL" },
  { name: "ANTI ALLERGIC LEPA OVER AFFECTED SKIN", shortName: "ANTI ALLERGIC LEPE OVER AFFECTED SKIN" },
  { name: "ANTI ALLERGIC LEPA TO AFFECTED SKIN", shortName: "ANTI ALLERGIC LEPE TO AFFECTED SKIN" },
  { name: "ANTI ALLERGIC MUD BODY MASSAGE", shortName: "AAMBM" },
  { name: "ANTI COLD THERAPY", shortName: "ACT" },
  { name: "ANTI ECZEMA LEPA", shortName: "ANT ECZM LEP" },
  { name: "ANTI ECZEMA LEPA OVER AFFECTED SKIN", shortName: "ANT ECZM LEPE OVER AFFECTED SKIN" },
  { name: "ANTI LEUCODERMA LEPA", shortName: "ANTI LEUCODERMA LEP" },
  { name: "ANTI PSORIASIS LEPA", shortName: "ANT ECZM LEP" },
  { name: "ANTI_HAIRFALL_THERAPY_IPD", shortName: "AHFT" },
  { name: "ANTIALLERGIC LEPA", shortName: "AAL" },
  { name: "ANTIFUNGAL LEPA", shortName: "AF LEPA" },
  { name: "ANTIFUNGAL LEPA AFFECTED PARTS", shortName: "AF LAPE" },
  { name: "ANTIPIMPLE LEPA", shortName: "ApL" },
  { name: "ANTIPIMPLE LEPA", shortName: "ApL" },
  { name: "ATHYNDROID LEPA", shortName: "ATyL" },
  { name: "ASTHMA PACK", shortName: "ASTHMA PACK" },
  { name: "ASTHMA BATH", shortName: "ASTHMA BATH" },
  { name: "ATP", shortName: "ATP" },
  { name: "BALUKA/SAIDHAVA IPD", shortName: "" },
  { name: "CALF MASSAGE AND THERMAL PACK", shortName: "CFM + TP" },
  { name: "CALF MASSAGE + TP", shortName: "CFM + TP" },
  { name: "CHEST PACK", shortName: "CP" },
  { name: "CHHACHH ENEMNA", shortName: "CHHACHH EN" },
  { name: "CHHACHH SNAN", shortName: "CS" },
  { name: "COCONUT OIL + CAMPHOR APPLICATION", shortName: "COCONUT OIL + CAMPHOR APPLICATION" },
  { name: "COCO-BUTTER MASSAGE + ST. BATH", shortName: "CB-MASSAGE+ST. BATH" },
  { name: "COCONUT WATER ENEMNA", shortName: "EN-COCO" },
  { name: "COFFEE ENEMNA", shortName: "COFFEE EN" },
  { name: "COFFEE SNAN 3 IN 1", shortName: "CSN 3 IN 1" },
  { name: "COLD CIRCULAR JET", shortName: "CCJ" },
  { name: "COLD COMPRESS (ABD)", shortName: "CC" },
  { name: "COLD COMPRESS (ABD)", shortName: "CC (ABD)" },
  { name: "COLD COMPRESS ON ABDOMEN", shortName: "CC (ABD)" },
  { name: "COLD COMPRESS ON KIDNEY + KNEE PK", shortName: "CC ON KIDNEY + KNEE PK" },
  { name: "COLD COMPRESS ON URINARY BLADDER", shortName: "COLD COMPRESS ON URINARY BLADDER" },
  { name: "COLD FOOT BATH WITH NEEM", shortName: "CFB NEEM" },
  { name: "COLD FOOT ARM BATH EPSOM SALT", shortName: "CFAB EPSOM SALT" },
  { name: "COLD FOOT BATH EPSOM SALT", shortName: "CFB EPSOM SALT" },
  { name: "COLD FOOT BATH WITH EPSOM SALT", shortName: "COLD FOOT BATH WITH EPSOM SALT" },
  { name: "COLD HIP BATH", shortName: "CHB" },
  { name: "COLD HIP BATH WITH NEEM", shortName: "CHB NEEM" },
  { name: "COLD SITZ BATH", shortName: "C SITZ BATH" },
  { name: "COLD SPINAL BATH", shortName: "C.SP.BATH" },
  { name: "COLD SPINAL SPRAY", shortName: "C.SP.SPRAY" },
  { name: "COLON HYDROTHERAPY", shortName: "CHT" },
  { name: "COSMETIC HERBAL PACK", shortName: "CHP" },
  { name: "COSMETIC HERBAL PACK", shortName: "CHP" },
  { name: "Diet Therapy", shortName: "Diet" },
  { name: "Dugdhaneti", shortName: "Dugdhaneti" },
  { name: "EN, JALNETI, EYE WASH, KUNJAL", shortName: "EN, JALNETI, EYE WASH, KUNJAL" },
  { name: "EN, JALNETI, RUBBER NETI, EYE WASH", shortName: "EN, JALNETI, RUBBER NETI, EYE WASH" },
  { name: "EN, JALNETI, RUBBER NETI, KUNJAL", shortName: "EN, JALNETI, RUBBER NETI, KUNJAL" },
  { name: "EN, JALNETI, RUBBER NETI, EYE WASH, KUNJAL", shortName: "EN, JALNETI, RUBBER NETI, EYE WASH, KUNJAL" },
  { name: "EN, JALNETI, RUBBER NETI, EYE WASH, KUNJAL", shortName: "EN, JALNETI, R-NETI, EYE WASH, KUNJAL, VD" },
  { name: "EN,JALNETI,EYEWASH", shortName: "EN,JALNETI,EYEWASH" },
  { name: "ENEMNA", shortName: "EN" },
  { name: "ENEMNA MUSTURD CHHACHH", shortName: "EN MUS, CHH" },
  { name: "EN-JALNETI", shortName: "EN, JALNETI" },
  { name: "EYE PACK", shortName: "EP" },
  { name: "EYE WASH", shortName: "EYE WASH" },
  { name: "EYE WASH WITH NORMAL WATER", shortName: "EYE WASH NORMAL WATER" },
  { name: "FACIAL SAUNA STEAM", shortName: "FSS" },
  { name: "FACIAL STEAM", shortName: "FACIAL STEAM" },
  { name: "FA STM WITH EUCALYPTUS LEAF", shortName: "FA STM WITH EUCALYPTUS LEAF" },
  { name: "FA STM WITH EUCALYPTUS OIL", shortName: "FA STM WITH EUCALYPTUS OIL" },
  { name: "FA STM WITH MUSTARD OIL/NASYA", shortName: "FA STM WITH MUSTARD OIL" },
  { name: "FA STM WITH TULSI LEAF", shortName: "FA STM WITH TULSI LEAF" },
  { name: "FBM+STEAM", shortName: "FBM+ST.B" },
  { name: "FBM+Steam Bath with chest pack", shortName: "FBM+STB with CPK" },
  { name: "Fire Cupping", shortName: "FirCu" },
  { name: "FOOT & ARM BATH", shortName: "FAB" },
  { name: "FULL BODY MASSAGE + STEAM BOX", shortName: "FBM + STEAM BOX" },
  { name: "FULL BODY MUD BATH + SNENAN + STEAM BATH", shortName: "FBMB+SNENAN+ST BATH" },
  { name: "FULL BODY MUD PACK", shortName: "FULL BODY MUD PACK" },
  { name: "FULL BODY NEEM APPLICATION", shortName: "FULL BODY NEEM APPLICATION" },
  { name: "FULL CHEST PACK", shortName: "FCP" },
  { name: "GANGI TURMERIC APPLICATION", shortName: "GANGI TURMERIC APPLICATION" },
  { name: "GANGI TURMERIC LEPE", shortName: "GANGI TURMERIC LAPE" },
  { name: "GHARSHANIC PACK", shortName: "G.PACK" },
  { name: "GHERU LEPA", shortName: "GHERU LAPE" },
  { name: "GHP (ABD)", shortName: "GHP (ABD)" },
  { name: "GODHAN TRIPHALA ENEMNA", shortName: "GODHA TRIPHALA EN AT 5 PM" },
  { name: "GREEN HOUSE THERMOLIUM", shortName: "GHT" },
  { name: "GYM (Health/Mokshan)", shortName: "Health Mokshan" },
  { name: "GYM THERAPY", shortName: "GYM" },
  { name: "HCC (ABD)", shortName: "HCC (ABD) PACK" },
  { name: "HCC (BACK)", shortName: "HCC (BACK)" },
  { name: "HCC (EAR)", shortName: "HCC (EAR)" },
  { name: "HCC (HEART)", shortName: "HCC (HEART)" },
  { name: "HCC (LIVER)", shortName: "HCC (LIVER)" },
  { name: "HCC (LIVER+CHEST)", shortName: "HCC (LIVER+CHEST)" },
  { name: "HCC (SPINE)", shortName: "HCC (SPINE)" },
  { name: "HCC FACE", shortName: "HCC FACE" },
  { name: "HCC KIDNEY (GINGER)", shortName: "HCC KIDNEY (GINGER)" },
  { name: "HCC KIDNEY (GINGER)", shortName: "HCC KIDNEY (GINGER)" },
  { name: "HCC LEFT HIP", shortName: "HCC LEFT HIP" },
  { name: "HCC LIVER & PANCREASE", shortName: "HCC L+P" },
  { name: "HCC TO B/L HIP", shortName: "HCC TO B/L HIP" },
  { name: "HCC TO B/L SHOULDER", shortName: "HCC TO B/L SHOULDER" },
  { name: "HCC(ABD)", shortName: "HCC(ABD)" },
  { name: "HCC(ABD), ATP, CFM, TP", shortName: "HCC(ABD), ATP, CFM, TP" },
  { name: "HCC(CHEST & ABD)", shortName: "HCC(CHEST & ABD)" },
  { name: "HCC(LOWER PARTS) + LEPAT", shortName: "HCC(LOWER PARTS) + LEPAT" },
  { name: "HCC(CERVICAL)", shortName: "HCC(CERVICAL)" },
  { name: "HCC(KNEE)", shortName: "HCC(KNEE)" },
  { name: "HCC(LUMBER+KNEE)", shortName: "HCC(L+KNEE)" },
  { name: "HCC(SHO)", shortName: "HCC(SHO)" },
  { name: "HCC(RIGHT SHOULDER)", shortName: "HCC(RIGHT SHOULDER)" },
  { name: "HEAD + NECK + SHOULDER MASSAGE WITH NADI SWEDAN", shortName: "HD+NK+SHD MSG WITH LS" },
  { name: "HEAD PACK", shortName: "HEAD PACK" },
  { name: "HEAD PACK EPSOM SALT", shortName: "HD & PK EPSOM SALT" },
  { name: "HFB WITH UNDER WATER HYDRO MSG", shortName: "HFB WITH UNDER WATER HYDRO MSG" },
  { name: "HIP BATH", shortName: "HIP BATH" },
  { name: "HOT & COLD FOOT ARM BATH EPSOM SALT", shortName: "H&C FAB EPSOM SALT" },
  { name: "HOT & COLD FOOT BATH EPSOM SALT", shortName: "H&C FB EPSOM SALT" },
  { name: "HOT & COLD HIP BATH WITH EPSOM SALT", shortName: "HOT & COLD HIP BATH WITH EPSOM SALT" },
  { name: "HOT & COLD HIP BATH WITH NEEM", shortName: "HCHB WITH NEEM" },
  { name: "hot and cold compress to neck", shortName: "HCC(Neck)" },
  { name: "HOT AND COLD COMPRESS TO SPINE", shortName: "HCC TO SPINE" },
  { name: "HOT COLD COMPRESS TO SPINE", shortName: "HCC TO SPINE" },
  { name: "HOT COLD FOOT AND ARM BATH WITH EPSOM SALT", shortName: "HOT COLD FOOT AND ARM BATH WITH EPSOM SALT" },
  { name: "HOT COLD HIP BATH WITH EPSOM SALT", shortName: "HCHB WITH EPSOM SALT" },
  { name: "HOT COLD HIP BATH WITH NEEM", shortName: "HCHB WITH NEEM" },
  { name: "HOT COLD HIP BATH WITH NEEM (KIDNEY)", shortName: "HCHB WITH NEEM(KIDNEY)" },
  { name: "HOT FOOT AND ARM BATH", shortName: "HOT FOOT AND ARM BATH" },
  { name: "HOT FOOT AND ARM BATH WITH EPSOM SALT", shortName: "HFAB WITH EPSOM SALT" },
  { name: "HOT FOOT ARM BATH WITH EPSOM SALT", shortName: "HFAB WITH EPSOM SALT" },
  { name: "HOT FOOT BATH WITH EPSOM SALT", shortName: "HFB WITH EPSOM SALT" },
  { name: "HOT HIP BATH", shortName: "HHB" },
  { name: "HOT HIP BATH", shortName: "HHB" },
  { name: "HOT HIP BATH WITH EPSOM SALT", shortName: "HHB MUD" },
  { name: "HOT SITTING BATH", shortName: "H. SIT. BATH" },
  { name: "HOT SPINAL BATH", shortName: "H.SP.BATH" },
  { name: "HOT WATER DRINKING", shortName: "HWD" },
  { name: "ICE APPLICATION ON ANUS", shortName: "ICE APPLICATION ON ANUS" },
  { name: "ICE APPLICATION ON PALMS AND SOLES", shortName: "ICE APPLICATION ON PALMS AND SOLES" },
  { name: "ICE COMPRESS ON ANKLE JOINT", shortName: "ICE COMPRESS ON ANKLE JOINT" },
  { name: "ICE COMPRESS ON ANUS", shortName: "ICE COMPRESS ON ANUS" },
  { name: "ICE COMPRESS ON SOLES", shortName: "ICE COMPRESS ON SOLES" },
  { name: "ICE COMPRESS ON SWOLLEN FINGER JOINTS + TOE JOINT", shortName: "ICE COMPRESS ON SWOLLEN FINGER JOINTS + TOE JOINT" },
  { name: "ICE COMPRESS OVER AFFECTED PARTS", shortName: "ICE COMPRESS OVER AFFECTED PARTS" },
  { name: "ICE COMPRESS OVER NECK AND SPINE", shortName: "ICE COMPRESS OVER NECK AND SPINE" },
  { name: "ICE COMPRESS OVER SWOLLEN PARTS", shortName: "ICE COMPRESS OVER SWOLLEN PARTS" },
  { name: "ICE COMPRESS TO AFFECTED PALMS AND SOLES", shortName: "ICE COMPRESS TO AFFECTED PALMS AND SOLES" },
  { name: "ICE COMPRESS TO NECK AND SPINE", shortName: "ICE COMP AND NECK AND SPINE" },
  { name: "ICE MASSAGE", shortName: "ICE M" },
  { name: "IPD-Anti Hairfall Therapy", shortName: "AHFT IPD" },
  { name: "IPD-HERBAL FACE PACK", shortName: "HERBAL FACE PACK" },
  { name: "IPD-Nadi Swedan", shortName: "NS-IPD" },
  { name: "IPD-Reetha Nasya", shortName: "REETHA NASYA" },
  { name: "IPD-SAUNA BATH", shortName: "SA B" },
  { name: "IPD-Steam Bath", shortName: "ST. B IPD" },
  { name: "IRR (WRIST)", shortName: "IRR (WRIST)" },
  { name: "IRR TO ABDOMEN", shortName: "IRR TO ABDOMEN" },
  { name: "IRR TO ALL PAINFUL JOINT", shortName: "IRR TO ALL PAINFUL JOINT" },
  { name: "IRR TO ALL PAINFUL PARTS", shortName: "IRR TO ALL PAINFUL PARTS" },
  { name: "IRR TO ANKLE JOINT", shortName: "IRR TO ANKLE JOINT" },
  { name: "IRR TO ARMS", shortName: "IRR TO ARMS" },
  { name: "IRR TO B/L KNEE", shortName: "IRR TO B/L KNEE" },
  { name: "IRR TO CERVICAL + ARMS + LEPS WITH LAPET", shortName: "IRR TO CERVICAL + ARMS + LEPS WITH LAPET" },
  { name: "IRR TO CERVICAL BACK+ARMS+KNEE+LEPAT", shortName: "IRR TO CERVICAL BACK+ARMS+KNEE+LAPET" },
  { name: "IRR TO CERVICAL + LUMBAR", shortName: "IRR TO CERVICAL + LUMBAR" },
  { name: "IRR TO CERVICAL + THORACIC", shortName: "IRR TO CERVICAL + THORACIC" },
  { name: "IRR TO ELBOW JOINT", shortName: "IRR TO ELBOW JOINT" },
  { name: "IRR TO ELBOW JOINT + LEPAT", shortName: "IRR TO ELBOW JOINT + LAPET" },
  { name: "IRR TO FEET", shortName: "IRR TO FEET" },
  { name: "IRR TO FINGERS", shortName: "IRR TO FINGERS" },
  { name: "IRR TO HAND", shortName: "IRR TO HAND" },
  { name: "IRR TO HIP", shortName: "IRR TO HIP" },
  { name: "IRR TO KNEE JOINT", shortName: "IRR TO KNEE JOINT" },
  { name: "IRR TO LEGS", shortName: "IRR TO LEGS" },
  { name: "IRR TO LOWER BACK", shortName: "IRR TO LOWER BACK" },
  { name: "IRR TO LUMBAR+ THORACIC", shortName: "IRR TO LUMBAR+ THORACIC" },
  { name: "IRR TO PAINFUL JOINTS", shortName: "IRR TO PAINFUL JOINTS" },
  { name: "IRR TO SPINE AND WHOLE BACK", shortName: "IRR TO SPINE AND WHOLE BACK" },
  { name: "IRR TO THORACIC", shortName: "IRR TO THORACIC" },
  { name: "IRR TO WHOLE BACK", shortName: "IRR TO WHOLE BACK" },
  { name: "JACCUZI", shortName: "JACCUZI" },
  { name: "Jalabasti", shortName: "Jalabasti" },
  { name: "Jalneti", shortName: "JN" },
  { name: "JALNETI, EYEWASH", shortName: "JN, EW" },
  { name: "JALNETI, EYEWASH, RUBBER NETI", shortName: "JN, EW, RN" },
  { name: "EN-JALNETI", shortName: "EN-JALNETI" },
  { name: "Kachalabhati", shortName: "Kapalabhati" },
  { name: "Karna Puran", shortName: "Karna Puran" },
  { name: "KAYAKALP ADVANCE TEL APPLICATION", shortName: "KK-L" },
  { name: "KAYAKALP LEPA", shortName: "KAYAKALP LEPA" },
  { name: "KAYAKALP/MASTIBBASTI", shortName: "KAYAKALP" },
  { name: "KESHKANTI_LEPA_IPD", shortName: "K LAPE" },
  { name: "KHIKH", shortName: "KHIKH" },
  { name: "KNEE PACK", shortName: "KNEE PACK" },
  { name: "KUNJAL", shortName: "KNJ" },
  { name: "KUNJAL WITH SAUFF WATER", shortName: "KUNJAL WITH SAUFF WATER" },
  { name: "L. FOOT BATH", shortName: "L. F. BATH" },
  { name: "L. F.", shortName: "L. F." },
  { name: "LEPA TO THROAT + LEPAT", shortName: "LEPA TO THROAT + LAPET" },
  { name: "LEFT EYE WASH", shortName: "LEFT EYE WASH" },
  { name: "LEG PACK", shortName: "LEG PACK" },
  { name: "LEPA (BODY)", shortName: "LEPA (BODY)" },
  { name: "LEPA LOCALLY", shortName: "LEPA LOCALLY" },
  { name: "LEPA LOCALLY", shortName: "L.L." },
  { name: "Liver and Gallbladder Cleansing", shortName: "Liver and Gallbladder Cleansing" },
  { name: "MASSAGE WITH ALOVERA", shortName: "MASSAGE WITH ALOVERA" },
  { name: "MASSAGE WITH COCONUT OIL", shortName: "MASSAGE WITH COCONUT OIL" },
  { name: "MASSAGE WITH COCONUT OIL + CAMPHOR", shortName: "MASSAGE WITH COCONUT OIL + CAMPHOR" },
  { name: "MASSAGE WITH NEEM OIL", shortName: "NEEM OIL MSG" },
  { name: "MASSAGES THERAPY: HCC(ABD), PM TO ABD & BACK", shortName: "HCC(ABD), PM TO ABD & BACK" },
  { name: "MASSAGES THERAPY: NEEM APPLICATION", shortName: "NEEM APPLICATION" },
  { name: "MASSAGES THERAPY: PM( ABD)", shortName: "PM( ABD)" },
  { name: "MASSAGES THERAPY: PM( ABD, BACK AND LEGS)", shortName: "PM( ABD, BACK AND LEGS)" },
  { name: "MASSAGES THERAPY: PM( ARMS AND LEGS)", shortName: "PM( ARMS AND LEGS)" },
  { name: "MASSAGES THERAPY: PM( ARMS LOW BACK AND LEGS)", shortName: "PM( ARMS LOW BACK AND LEGS)" },
  { name: "MASSAGES THERAPY: PM( ARMS, CHEST AND ABD)", shortName: "PM( ARMS, CHEST AND ABD)" },
  { name: "MASSAGES THERAPY: PM( ARMS, CHEST, ABD AND LEGS)", shortName: "PM( ARMS, CHEST, ABD AND LEGS)" },
  { name: "MASSAGES THERAPY: PM( HEAD ARMS AND LEGS)", shortName: "PM( HEAD ARMS AND LEGS)" },
  { name: "MASSAGES THERAPY: PM( HEAD NEAK, SPINE AND BACK)", shortName: "PM( HEAD NEAK, SPINE AND BACK)" },
  { name: "MASSAGES THERAPY: PM( HEAD, SPINE, BACK AND LEGS)", shortName: "PM( HEAD, SPINE, BACK AND LEGS)" },
  { name: "MASSAGES THERAPY: PM(ARMS)", shortName: "PM(ARMS)" },
  { name: "MASSAGES THERAPY: PM(BACK)", shortName: "PM(BACK)" },
  { name: "MASSAGES THERAPY: PM(CHEST)", shortName: "PM(CHEST)" },
  { name: "MASSAGES THERAPY: PM(HEAD, CHEST, ABD)", shortName: "PM(HEAD, CHEST, ABD)" },
  { name: "MASSAGES THERAPY: PM(HEAD, NECK, SHOULDER, ARMS AND BACK)", shortName: "PM(HEAD, NECK, SHOULDER, ARMS AND BACK)" },
  { name: "MASSAGES THERAPY: PM(HEAD)", shortName: "PM(HEAD)" },
  { name: "MASSAGES THERAPY: PM(LEGS)", shortName: "PM(LEGS)" },
  { name: "MASSAGES THERAPY: PM(SPINE)", shortName: "PM(SPINE)" },
  { name: "MASSAGES THERAPY: ROSE HONEY MASSAGE", shortName: "RHM" },
  { name: "MASTIBBASTI(AHD-OFFECTED PARTS) + LAPET", shortName: "MASTIBBASTI(AHD-OFFECTED PARTS) + LAPET" },
  { name: "MEDICATED MASSAGE", shortName: "MEDI MASSAGE" },
  { name: "MEDICATED MASSAGE+STEAM BOX", shortName: "MEDI MASSAGE+STEAM BOX" },
  { name: "Melanogrit Lape", shortName: "Melanogrit Lape" },
  { name: "Mooladhana/Chakra karma", shortName: "Mooladhana/Chakra karma" },
  { name: "MUD APPLICATION (LUMBAR)", shortName: "MUD (LUMBAR)" },
  { name: "MUD APPLICATION ON ARMS", shortName: "MUD APPLICATION ON ARMS" },
  { name: "MUD APPLICATION ON EFFECTED PARTS", shortName: "MUD APPLICATION ON EFFECTED PARTS" },
  { name: "MUD APPLICATION ON SPINE AND WHOLE BACK", shortName: "MUD APPLICATION ON SPINE AND WHOLE BACK" },
  { name: "MUD APPLICATION ON THROAT", shortName: "MUD APPLICATION ON THROAT" },
  { name: "MUD APPLICATION ON WRIST", shortName: "MUD APPLICATION ON WRIST" },
  { name: "MUD APPLICATION TO ANUS", shortName: "MUD TO ANUS" },
  { name: "MUD APL TO ARMS", shortName: "MUD APL TO ARMS" },
  { name: "MUD APL TO ARMS AND LEGS", shortName: "MUD APL TO ARMS AND LEGS" },
  { name: "MUD APL TO HEAD", shortName: "MUD APL TO HEAD" },
  { name: "MUD APL TO LEGS", shortName: "MUD APL TO LEGS" },
  { name: "MUD APPLICATION UNDER SCROTUM", shortName: "MUD APPLICATION UNDER SCROTUM" },
  { name: "MUD APPLICATION WITH (NEEM+TULSI+GINGER+GARLIC +TURMERIC)", shortName: "MUD APPLICATION WITH (NEEM+TULSI+GINGER+GARLIC +TU" },
  { name: "MUD CAP TO BACK", shortName: "MUD CAP TO BACK" },
  { name: "MUD CAP TO HEAD", shortName: "MUD CAP TO HEAD" },
  { name: "MUD COMPRESS", shortName: "M.C." },
  { name: "MUD COMPRESS, EYE PACK", shortName: "MCHEP" },
  { name: "MUD PACK", shortName: "" },
  { name: "MUD PACK ON UNDER PERINIUM", shortName: "MUD PACK ON UNDER PERINIUM" },
  { name: "MUD POOL", shortName: "MUD POOL 2.5 HOURS" },
  { name: "MULTANI MITTI APPLICATION ON AFFECTED SKIN", shortName: "MULTANI MITTI APPLICATION ON AFFECTED SKIN" },
  { name: "MULTANI MITTI APPLICATION TO AFFECTED PARTS", shortName: "MULTANI MITTI APPLICATION TO AFFECTED PARTS" },
  { name: "MULTANI MITTI ON HEAD", shortName: "MULTANI MITTI ON HEAD" },
  { name: "MULTANI_MITTI", shortName: "MULTANI_MITTI" },
  { name: "MUSTARD PACK", shortName: "MUSTARD PACK" },
  { name: "NADI SWEDAN (Abdomen)", shortName: "NS (ABD)" },
  { name: "NADI SWEDAN (ANKLE)", shortName: "NS (ANKLE JOINT)" },
  { name: "NADI SWEDAN (Chest)", shortName: "NS (Chest)" },
  { name: "NADI SWEDAN (KNEE)", shortName: "NS (KNEE)" },
  { name: "NADI SWEDAN (LUMBAR)", shortName: "NS (LUMBAR)" },
  { name: "NADI SWEDAN (LEGS)", shortName: "NS (LEGS)" },
  { name: "NADI SWEDAN (PEEDANTAK)TO PAINFUL JOINTS", shortName: "NS (PEEDANTAK)TO PAINFUL JOINTS" },
  { name: "NADI SWEDAN TO ARMS", shortName: "NS TO ARMS" },
  { name: "NADI SWEDAN ON ABDOMEN", shortName: "NS ON ABDOMEN" },
  { name: "NADI SWEDAN ON CHEST AND BACK", shortName: "NS ON CHEST AND WHOLE BACK" },
  { name: "NADI SWEDAN ON PAINFUL JOINTS", shortName: "NS TO PAINFUL JOINTS" },
  { name: "NADI SWEDAN TO BACK", shortName: "NS TO BACK" },
  { name: "NADI SWEDAN TO FEET", shortName: "NS TO FEET" },
  { name: "NADI SWEDAN TO FEET", shortName: "NS TO FEET" },
  { name: "NADI SWEDAN TO NECK + NECK PACK", shortName: "NS TO NECK + NECK PACK" },
  { name: "NADI SWEDAN TO NECK + SHOULDER + LOW BACK + KNEE", shortName: "NS TO NECK + SHOULDER + LOW BACK + KNEE" },
  { name: "NADI SWEDAN TO PAINFUL PARTS", shortName: "NS TO PAINFUL PARTS" },
  { name: "NADI SWEDAN TO CERVICAL + ARMS + KNEE + LEPAT WITH LEPAT", shortName: "NS TO CERVICAL + ARMS + KNEE + LEPAT WITH LEPAT" },
  { name: "NADI SWEDAN TO WRIST JOINT", shortName: "NS TO WRIST JOINT" },
  { name: "NS UNDER SOLES(TALWA)", shortName: "NS UNDER SOLES(TALWA)" },
  { name: "NADI_SWEDAN", shortName: "NS" },
  { name: "Nauli", shortName: "Nauli" },
  { name: "HEAD + SHOULDER MASSAGE WITH NADI SWEDAN", shortName: "HD+SHD MSG WITH LS" },
  { name: "NECK MASSAGE", shortName: "NK MSG" },
  { name: "NECK MASSAGE WITH NADI SWEDAN", shortName: "NK MSG WITH LS" },
  { name: "NEEM BASTI", shortName: "NB - NEEM" },
  { name: "NEEM BASTI", shortName: "NB - NEEM" },
  { name: "NEEM CHEST PACK", shortName: "CHEST PACK WITH NEEM" },
  { name: "NEEM FULL WET SHEET PACK", shortName: "NEEM FWSP" },
  { name: "NEEM LEPA", shortName: "NEEM LAPE" },
  { name: "NEEM SNAN 3 IN ONE", shortName: "SNAN 3 IN 1" },
  { name: "NEUTRAL FOOT ARM BATH EPSOM SALT", shortName: "NFAB EPSOM SALT" },
  { name: "NEUTRAL FOOT BATH EPSOM SALT", shortName: "NFB EPSOM SALT" },
  { name: "NEUTRAL HIP BATH EPSOM SALT", shortName: "NHB EPSOM SALT" },
  { name: "NEUTRAL HIP BATH WITH EPSOM SALT", shortName: "NHB WITH EPSOM SALT" },
  { name: "NEUTRAL HIP BATH WITH NEEM", shortName: "NHB WITH NEEM" },
  { name: "NEUTRAL IMMERSION BATH", shortName: "NIB" },
  { name: "NEUTRAL IMMERSION BATH WITH (MgSO4+ NaCl+NaHCO3)", shortName: "NIB WITH (MgSO4+ NaCl+NaHCO3)" },
  { name: "NEUTRAL IMMERSION BATH WITH EPSOM SALT", shortName: "NIB WITH EPSOM SALT" },
  { name: "NEUTRAL IMMERSION BATH WITH NEEM", shortName: "NIB WITH NEEM" },
  { name: "NEUTRAL SITZ BATH", shortName: "N. SITZ BATH" },
  { name: "NEUTRAL SPINAL BATH", shortName: "N.SP.BATH" },
  { name: "NEUTRAL SPINAL SPRAY", shortName: "N.SP.SPRAY" },
  { name: "NEUTRAL UNDER WATER MASSAGE BATH WITH (MgSO4+ NaCl+NaHCO3)", shortName: "NUWMB WITH (MgSO4+ NaCl+NaHCO3)" },
  { name: "NEUTRAL UNDER WATER MASSAGE BATH WITH EPSOM SALT", shortName: "NUWMB WITH EPSOM SALT" },
  { name: "OIL MASSAGE + STEAM BOX", shortName: "FBM + STB" },
  { name: "OGST PACK (CHEST+ BACK)", shortName: "OGST PACK(CHEST+ BACK) AND CHEST LAPET" },
  { name: "One week Yoga therapy package (IPD)", shortName: "OGST PACK (one weeks Yoga therapy package (IPD))" },
  { name: "OMM WITH GINGER TURMERIC COMPRESS AND LEPAT", shortName: "OMM WITH GINGER TURMERIC COMPRESS AND LEPAT" },
  { name: "osteopathy_IPD", shortName: "OSTE" },
  { name: "OZONE BATH", shortName: "OZONE BATH" },
  { name: "OZONE THERAPY PACKAGE 01 (FOR 01 - 04 DAYS)", shortName: "OZONE (FOR 01 - 04 DAYS)" },
  { name: "OZONE THERAPY PACKAGE 02 (FOR 05 - 06 DAYS)", shortName: "OZONE (FOR 05 - 06 DAYS)" },
  { name: "OZONE THERAPY PACKAGE 03 (FOR 07 OR MORE DAYS)", shortName: "OZONE (FOR 07 OR MORE DAYS)" },
  { name: "PAPAYA FACE PACK", shortName: "PAP F PK" },
  { name: "Partial Massage (PM)", shortName: "Partial Massage (Pm)" },
  { name: "PARTIAL VIBRO MASSAGE TO ABDOMEN AND FATTY PARTS", shortName: "PVBM" },
  { name: "PATANJALI BALM-DIVYA DHARA WITH CHEST LAPET", shortName: "PAT BALM CH PK" },
  { name: "PEEDANTAK LEPA", shortName: "PEEDANTAK LAPE" },
  { name: "PEEDANTAK LEPA APPLICATION", shortName: "PEEDANTAK LAPE" },
  { name: "PH THERAPY - KUNDALINI", shortName: "PH THERAPY" },
  { name: "PHYSIOTHERAPY_IPD", shortName: "PHYSIO" },
  { name: "PLATOGRIT BASTI", shortName: "NB - PLATO" },
  { name: "POTLI TO HEAD, SPINE, ARMS AND CHEST", shortName: "POTLI TO HEAD, SPINE, ARMS AND CHEST" },
  { name: "POTLI THIGH", shortName: "POTLI TO THIGH" },
  { name: "POTLI TO ABDOMEN", shortName: "POTLI TO ABDOMEN" },
  { name: "POTLI TO ARMS", shortName: "POTLI TO ARMS" },
  { name: "POTLI TO ARMS +BACK WITH LEPAT", shortName: "POTLI TO ARMS +BACK WITH LAPET" },
  { name: "POTLI TO ARMS AND LEFT ARM", shortName: "POTLI TO ARMS AND LEFT ARM" },
  { name: "POTLI TO ARMS, CERVICAL AND LEGS WITH LEPAT", shortName: "POTLI TO ARMS, CERVICAL AND LEGS WITH LAPET" },
  { name: "POTLI TO B/L KNEE", shortName: "POTLI TO B/L KNEE" },
  { name: "POTLI TO BACK AND HIPS", shortName: "POTLI TO BACK AND HIPS" },
  { name: "POTLI TO CERVICAL", shortName: "POTLI TO CERVICAL" },
  { name: "POTLI TO CERVICAL + KNEE + LEPAT", shortName: "POTLI TO CERVICAL + KNEE + LAPET" },
  { name: "POTLI TO CERVICAL + KNEES", shortName: "POTLI TO CERVICAL + KNEES" },
  { name: "POTLI TO CERVICAL BACK AND SHOULDERS", shortName: "POTLI TO CERVICAL BACK AND SHOULDERS" },
  { name: "POTLI TO CERVICAL BACK + ARMS + KNEE + LEPAT", shortName: "POTLI TO CERVICAL BACK + ARMS + KNEE + LAPET" },
  { name: "POTLI TO CERVICAL + LUMBAR", shortName: "POTLI TO CERVICAL + LUMBAR" },
  { name: "POTLI TO CERVICAL AND WHOLE BACK", shortName: "POTLI TO CERVICAL AND WHOLE BACK" },
  { name: "POTLI TO CERVICAL+ARMS WITH LEPAT", shortName: "POTLI TO CERVICAL+ARMS WITH LAPET" },
  { name: "POTLI TO CERVICAL+LUMBAR+KNEES WITH LEPAT", shortName: "POTLI TO CERVICAL+LUMBAR+KNEES WITH LAPET" },
  { name: "POTLI TO COCCYX", shortName: "POTLI TO COCCYX" },
  { name: "POTLI TO COCCYX + HIP + KNEE + CALF WITH LAPET", shortName: "POTLI TO COCCYX + HIP + KNEE + CALF WITH LAPET" },
  { name: "POTLI TO ELBOW + WRIST + LEPAT", shortName: "POTLI TO ELBOW + WRIST + LAPET" },
  { name: "POTLI TO ELBOW JOINT", shortName: "POTLI TO ELBOW JOINT" },
  { name: "POTLI TO FEET", shortName: "POTLI TO FEET" },
  { name: "POTLI TO HAND", shortName: "POTLI TO HAND" },
  { name: "POTLI TO HEELS", shortName: "POTLI TO HEELS" },
  { name: "POTLI TO HIP", shortName: "POTLI TO HIP" },
  { name: "POTLI TO KNEE JOINT", shortName: "POTLI TO KNEE JOINT" },
  { name: "POTLI TO KNEES+HEELS+ ELBOWS WITH LEPAT", shortName: "POTLI TO KNEES+HEELS+ ELBOWS WITH LAPET" },
  { name: "POTLI TO LOW BACK", shortName: "POTLI TO LOW BACK" },
  { name: "POTLI TO LOW BACK + FEET / HIPS", shortName: "POTLI TO LOW BACK + FEET / HIPS" },
  { name: "POTLI TO LOW BACK AND HIPS + KNEES WITH LEPAT", shortName: "POTLI TO LOW BACK AND HIPS + KNEES WITH LAPET" },
  { name: "POTLI TO LOW BACK AND LEGS", shortName: "POTLI TO LOW BACK AND LEGS" },
  { name: "POTLI TO LOW BACK AND LEGS + LEPAT", shortName: "POTLI TO LOW BACK AND LEGS + LAPET" },
  { name: "POTLI TO LUMBAR", shortName: "POTLI TO LUMBAR" },
  { name: "POTLI TO LUMBAR BACK AND SOLES (TALWA)", shortName: "POTLI TO LUMBAR BACK AND SOLES (TALWA)" },
  { name: "POTLI TO LUMBAR+ THORACIC", shortName: "POTLI TO LUMBAR+ THORACIC" },
  { name: "POTLI TO MIDDLE BACK+ B/L KNEE WITH LEPAT", shortName: "POTLI TO MIDDLE BACK+ B/L KNEE WITH LAPET" },
  { name: "POTLI TO NECK + KNEE WITH LAPET", shortName: "POTLI TO NECK + KNEE WITH LAPET" },
  { name: "POTLI TO NECK + SHOULDERS + ARMS +BACK", shortName: "POTLI TO NECK + SHOULDERS + ARMS +BACK" },
  { name: "POTLI TO NECK AND BACK", shortName: "POTLI TO NECK AND BACK" },
  { name: "POTLI TO NECK AND SHOULDERS", shortName: "POTLI TO NECK AND SHOULDERS" },
  { name: "POTLI TO NECK AND WHOLE BACK", shortName: "POTLI TO NECK AND WHOLE BACK" },
  { name: "POTLI TO NECK+KNEE+THIGH WITH LEPAT", shortName: "POTLI TO NECK+KNEE+THIGH WITH LAPET" },
  { name: "POTLI PAIN FULL JOINTS", shortName: "POTLI PAIN FULL JOINT" },
  { name: "POTLI TO PAINFUL JOINTS", shortName: "POTLI TO PAINFUL JOINTS" },
  { name: "POTLI TO PAINFUL PARTS", shortName: "POTLI TO PAINFUL PARTS" },
  { name: "POTLI TO SHOULDER + ARMS + KNEES WITH LEPAT", shortName: "POTLI TO SHOULDER + ARMS + KNEES WITH LAPET" },
  { name: "POTLI TO SHOULDER + KNEE WITH LEPAT", shortName: "POTLI TO SHOULDER + KNEE WITH LAPET" },
  { name: "POTLI TO SHOULDER JOINT", shortName: "POTLI TO SHOULDER JOINT" },
  { name: "POTLI TO SHOULDER+ WHOLE BACK", shortName: "POTLI TO SHOULDER+ WHOLE BACK" },
  { name: "POTLI TO SHOULDER+ WHOLE BACK", shortName: "POTLI TO SHOULDER+ WHOLE BACK" },
  { name: "POTLI TO SHOULDERS AND UPPER BACK", shortName: "POTLI TO SHOULDERS AND UPPER BACK" },
  { name: "POTLI TO SHOULDERS AND LOW BACK", shortName: "POTLI TO SHOULDERS AND LOW BACK" },
  { name: "POTLI TO SOLES(TALWA)", shortName: "POTLI TO SOLES(TALWA)" },
  { name: "POTLI TO SPINE", shortName: "POTLI TO SPINE" },
  { name: "POTLI TO TAIL BONE", shortName: "POTLI TO TAIL BONE" },
  { name: "POTLI TO THIGH", shortName: "POTLI TO THIGH" },
  { name: "POTLI TO WRIST", shortName: "POTLI TO WRIST" },
  { name: "POTLI TO WHOLE BACK", shortName: "POTLI TO WHOLE BACK" },
  { name: "POTLI TO WHOLE BACK AND B/L KNEE", shortName: "POTLI TO WHOLE BACK AND B/L KNEE" },
  { name: "POTLI TO WHOLE BACK AND LEGS WITH LEPAT", shortName: "POTLI TO WHOLE BACK AND LEGS WITH LAPET" },
  { name: "POTLI TO WHOLE BACK+LEGS WITH LEPAT", shortName: "POTLI TO WHOLE BACK+LEGS WITH LAPET" },
  { name: "POTLI(ABD)", shortName: "POTLI(ABD)" },
  { name: "PYRAMID THERAPY", shortName: "PT" },
  { name: "Reflexology", shortName: "Reflexology" },
  { name: "REST THERAPY (AT SADHAK ROOM)", shortName: "REST THERAPY (AT SADHAK ROOM)" },
  { name: "RIGHT EYE WASH", shortName: "RIGHT EYE WASH" },
  { name: "SAND BATH", shortName: "SAND BATH" },
  { name: "RHM + ST B", shortName: "RHM + ST B" },
  { name: "SALT GLOW MASSAGE", shortName: "SGM" },
  { name: "SALT GLOW OIL MASSAGE", shortName: "SGM + SOB" },
  { name: "SAND BATH", shortName: "SAND BATH" },
  { name: "Sauna Bath with chest pack", shortName: "SA B with CHPK" },
  { name: "Sauna Bath with cold chest pack", shortName: "SA B with CHPK" },
  { name: "SAUNA BATH", shortName: "SAUNA BATH" },
  { name: "Shankhaprakshalana (with therapeutic diet)", shortName: "Shankhaprakshalana (with therapeutic diet)" },
  { name: "SP AMLA WATER WITH SALT", shortName: "SP AMLA WATER WITH SALT" },
  { name: "SHIAO BASTI", shortName: "SH BASTI" },
  { name: "SHOULDER MASSAGE WITH LOCAL STEAM", shortName: "SHD MSG WITH LS" },
  { name: "Sitz Bath", shortName: "Sitz Bath" },
  { name: "Anti Vitilligo Lape", shortName: "Anti Vitilligo Lape" },
  { name: "SHWITRAGHAN LEPA", shortName: "SHWITRAGHAN LAPE" },
  { name: "SP WITH AMLA WATER", shortName: "SP WITH AMLA WATER" },
  { name: "SP WITH LEMON WATER", shortName: "SP WITH LEMON WATER" },
  { name: "SP WITH NEEM LEAF", shortName: "SP WITH NEEM LEAF" },
  { name: "SP WITH WARM WATER", shortName: "SP WITH WARM WATER" },
  { name: "SPECIAL THYROID PACK", shortName: "SPECIAL THYROID PACK" },
  { name: "SPONGE BATH", shortName: "SPO BATH" },
  { name: "STEAM BATH", shortName: "ST. B" },
  { name: "ST. BATH (15 MINUTES)", shortName: "ST. B (15 MINUTES)" },
  { name: "steam bath kayakalp", shortName: "st kayakal" },
  { name: "Steam bath with cold chest pack", shortName: "STE B with CHPK" },
  { name: "STEAM BOX", shortName: "STEAM BOX" },
  { name: "STEAM BOX (KAYAKALP) KWATH", shortName: "STEAM BOX (KKQ)" },
  { name: "STEAM BOX (MEDHA KWATH)", shortName: "STEAM BOX (MEDHA Q)" },
  { name: "Sthalabasti", shortName: "Sthalabasti" },
  { name: "STHALAKAY LAPE", shortName: "SKL" },
  { name: "THERMAL PACK", shortName: "TP" },
  { name: "THIGH PACK", shortName: "THIGH PACK" },
  { name: "Three weeks Yoga therapy package (IPD)", shortName: "Three weeks Yoga therapy package (IPD)" },
  { name: "THROAT PACK", shortName: "THROAT PACK" },
  { name: "TP(ABD)", shortName: "TP(ABD)" },
  { name: "Trataka (jyoti)", shortName: "Trataka (jyoti)" },
  { name: "TRIPHALA ENEMNA", shortName: "TRIPH EN" },
  { name: "Two weeks Yoga therapy package (IPD)", shortName: "Two weeks Yoga therapy package (IPD)" },
  { name: "Under water massage (UWM)", shortName: "UWM" },
  { name: "VAGINAL DOUCHE", shortName: "VD" },
  { name: "VAGINAL PANCHAMRUTA", shortName: "V PANCHAMRUTA" },
  { name: "VIBRO MASSAGE", shortName: "VBM" },
  { name: "WARM SITZ BATH", shortName: "WARM SITZ BATH" },
  { name: "WET FRICTION", shortName: "WF" },
  { name: "WHIRLPOOL", shortName: "WHIRLPOOL" },
  { name: "Yoga", shortName: "Yoga" },
  { name: "YONIPRAKSHALAN_IPD", shortName: "YPr" },
  { name: "ABHYANG + ST BATH", shortName: "ABHYANG + ST BATH" },
  { name: "ABHYANG BALAA OIL", shortName: "ABH-BALA" },
  { name: "ABHYANG KAYAKALP OIL", shortName: "ABY-K" },
  { name: "ABHYANG PEEDANTAK OIL", shortName: "ABY-P" },
  { name: "ABHYANG PEEDANTAK OIL", shortName: "ABY-P" },
  { name: "ABHYANGAM", shortName: "ABH" },
  { name: "ACIDOGRIT BASTI", shortName: "NB-ACID" },
  { name: "ADHO JAMBIRA PIND SWEDAN", shortName: "AdjPS" },
  { name: "ADHO PATRA PIND SWEDAN", shortName: "AdPPS" },
  { name: "ADHO PATRA PIND SWEDAN", shortName: "AdPPS" },
  { name: "ADHO PIZHICHIL", shortName: "AdPIZHI" },
  { name: "ADHO SWEDAN", shortName: "AdS" },
  { name: "AKSHI TARPAN", shortName: "AT" },
  { name: "AKSHI TARPAN (M.T.GHRIT)", shortName: "AT(M.T.GHRIT)" },
  { name: "AKSHITARPAN (M.T.GHRIT)_IPD", shortName: "AKSHITARPAN (M.T.GHRIT)" },
  { name: "ANUVASAN BASTI", shortName: "AB" },
  { name: "AWAGAHA SWEDAN( BY OIL)", shortName: "AWG-OIL" },
  { name: "AWAGAHA SWEDAN(BY KWATH)", shortName: "AWG-KW" },
  { name: "BAHYA SNEHAN (KAYAKALP)", shortName: "BSB" },
  { name: "BONEHEALTH BASTI", shortName: "NB-BH" },
  { name: "BPGRIT BASTI", shortName: "NB-BP" },
  { name: "CARDIOGRIT BASTI", shortName: "NB-CARD" },
  { name: "CARDIOGRIT BASTI", shortName: "NB-CARD" },
  { name: "CHAYAN PATRA SWEDAN", shortName: "CPS" },
  { name: "CYSTOGRIT BASTI", shortName: "NB-CYST" },
  { name: "DASHMOOL BASTI", shortName: "NB-D" },
  { name: "DEH DERMA BASTI", shortName: "NB-DERMA" },
  { name: "DHANYA AMLADHARA", shortName: "DAD" },
  { name: "DREHA SWEDAN", shortName: "DS" },
  { name: "EARGRIT BASTI", shortName: "NB-EAR" },
  { name: "EYEGRIT BASTI", shortName: "NB-EYE" },
  { name: "GALA GANDUSH/KAVAL", shortName: "GANDUSH" },
  { name: "GHRIT BASTI", shortName: "NB-GHRIT" },
  { name: "GODHAN BASTI", shortName: "NB-GO" },
  { name: "GREEVA BASTI", shortName: "GB" },
  { name: "HAEM BASTI", shortName: "NB-HAEM" },
  { name: "HAIR MASSAGE WITH COCONUT OIL", shortName: "HAIR MASSAGE WITH COCONUT OIL" },
  { name: "HERBAL MASSAGE", shortName: "HERBAL MASSAGE" },
  { name: "HRIDAY BASTI", shortName: "HRIDAY BASTI" },
  { name: "IPD_ ABHYANGAM", shortName: "ABH" },
  { name: "IPD_ADHO MASH PIND SWEDAN", shortName: "AdMPS" },
  { name: "IPD_ADHO PATRA PIND SWEDAN", shortName: "AdPPS" },
  { name: "IPD_GOKHRU BASTI", shortName: "GOKHRU BASTI" },
  { name: "IPD_IMMUNOGRIT BASTI", shortName: "NB-IMMUNO" },
  { name: "IPD_JANU BASTI", shortName: "JB" },
  { name: "IPD_JANU BASTI", shortName: "JB" },
  { name: "IPD_KATI BASTI", shortName: "KB" },
  { name: "IPD_KATI UPNAHA", shortName: "KU" },
  { name: "IPD_LUNG BASTI", shortName: "LuB" },
  { name: "IPD_MADHU BASTI", shortName: "MB" },
  { name: "IPD_MEDHA BASTI", shortName: "NB-Medha" },
  { name: "IPD_NABHI BASTI", shortName: "NABHI BASTI" },
  { name: "IPD_NADI SWEDAN", shortName: "NS-IPD" },
  { name: "IPD_NETRA DHARA(KWATH)", shortName: "Nd-KW" },
  { name: "IPD_PIZHICHIL", shortName: "PIZHI" },
  { name: "IPD_SANTATI BASTI", shortName: "SANTATI BASTI" },
  { name: "IPD_SARVANG VASP SWEDAN", shortName: "SVS" },
  { name: "IPD_SHIRO ABHYANGAM", shortName: "SH-ABH" },
  { name: "IPD_SHIRODHARA COCONUT OIL", shortName: "SHIRODHARA COCONUT OIL" },
  { name: "IPD_SHIRODHARA(OIL)", shortName: "SH-OIL" },
  { name: "IPD_SHANIK ABHYANG", shortName: "ST-ABY" },
  { name: "IPD_TALAPODICHIL", shortName: "TaPODI" },
  { name: "IPD_URO BASTI", shortName: "UB" },
  { name: "IPD_UNMARDAN", shortName: "UNMD" },
  { name: "IPD_UTTAR BASTI", shortName: "UB" },
  { name: "IPD_VAMAN", shortName: "VAM" },
  { name: "IPD_VIRECHANA", shortName: "VIR" },
  { name: "Isabgol Basti", shortName: "Isab-Basti" },
  { name: "JALOUKAVACARANA LOCALLY", shortName: "JALOUKAVACARANA LOCALLY" },
  { name: "JALOUKAVACARANA", shortName: "JAL" },
  { name: "JANU DHARA", shortName: "Janu Dhara" },
  { name: "JANU PIZICHIL(OIL)", shortName: "JaPIZHI" },
  { name: "KANCHNAAR LEPA", shortName: "KANCHNAAR LEPA" },
  { name: "KARAN PURAN", shortName: "KP" },
  { name: "KARAN PURAN", shortName: "KP" },
  { name: "KARNAPOORN", shortName: "KD" },
  { name: "KATI BASTI", shortName: "KB" },
  { name: "KATI DHARA", shortName: "KATI DHARA" },
  { name: "KATIPICHU", shortName: "KaPI" },
  { name: "KAVAL/GANDUSH", shortName: "KAV-GAN" },
  { name: "KSHEER BASTI", shortName: "NB-Ksh" },
  { name: "KSHEER DHOOM", shortName: "KshDhoo" },
  { name: "KSHIRA DHARA", shortName: "KSHIRA DHARA" },
  { name: "KSHIRA DOMA", shortName: "KSHIRA DOMA" },
  { name: "KUTAJ BEL BASTI", shortName: "KUTAJ BEL BASTI" },
  { name: "KUTAJ BASTI", shortName: "NB-KU" },
  { name: "LEKHAN BASTI_IPD", shortName: "LB" },
  { name: "LEPA (BODY)", shortName: "LEPA (BODY)" },
  { name: "LIVER BASTI", shortName: "NB-LIVO" },
  { name: "LUVOGRIT BASTI", shortName: "NB-LIVO" },
  { name: "M. MASH PIND BASTI (MTB)", shortName: "M. MASH PIND BASTI (MTB)" },
  { name: "MADHU BASTI", shortName: "MB" },
  { name: "MATRA BASTI", shortName: "MB" },
  { name: "MATRA_BASTI", shortName: "MB" },
  { name: "MEDHOHAR BASTI_IPD", shortName: "NB-Medha" },
  { name: "Melanogrit Lape", shortName: "Melanogrit LAPE" },
  { name: "MUKHADHARA", shortName: "MUDHA" },
  { name: "MULP_IPD", shortName: "MULP" },
  { name: "NADI SWEDAN", shortName: "NS" },
  { name: "NARI KANTI BASTI", shortName: "NB-NARI" },
  { name: "NASYA", shortName: "NAS" },
  { name: "NETRA DHARA(GHRITA)", shortName: "NetDha" },
  { name: "Niru Basti", shortName: "N.B." },
  { name: "NIRU BASTI_IPD", shortName: "NB" },
  { name: "NB-ND", shortName: "NB-ND" },
  { name: "NUTRELA DAILY ACTIVE BASTI", shortName: "NB-ND" },
  { name: "NUTRELA DAILY ENERGY BASTI", shortName: "NB-NDE" },
  { name: "NUTRELA ISOVEDA BASTI", shortName: "NB-IVA" },
  { name: "ORTHOGRIT BASTI", shortName: "NB-ORTHO" },
  { name: "PADA ABYANG", shortName: "PADA-ABY" },
  { name: "PADA GHRT", shortName: "PADA-GHT" },
  { name: "PANCHAKARMA", shortName: "PK" },
  { name: "PANCHTIKTA BASTI", shortName: "PANCHTIKTA BASTI" },
  { name: "PANCHTIKTA BASTI", shortName: "NB-PANCH" },
  { name: "PATRA PIND POTLI", shortName: "PPP" },
  { name: "PATRA PIND SWEDAN", shortName: "PPS" },
  { name: "PEEDANIL LEPA", shortName: "PEED-LP" },
  { name: "PEEDANTAK STEAM BATH", shortName: "PEED STM BATH" },
  { name: "PIZHICHIL", shortName: "PIZHICHIL" },
  { name: "PRACHANA", shortName: "PRCH" },
  { name: "PRASARNI LEPA", shortName: "PM-NSM" },
  { name: "PRISTHA BASTI", shortName: "PB" },
  { name: "PROSTOGRIT BASTI", shortName: "NB-PROSTO" },
  { name: "PSOROGRIT BASTI", shortName: "NB-PSORO" },
  { name: "RAKTAMOKSHAN", shortName: "RM" },
  { name: "RAKTAMOKSHAN(CUP)", shortName: "RM-CUP" },
  { name: "SADYO VIRECHANA", shortName: "SDY-VIR" },
  { name: "SARV KALP BASTI", shortName: "SARV KALP BASTI" },
  { name: "SARVANG DHARA", shortName: "SD" },
  { name: "SASTIK SALI PIND SWEDAN", shortName: "SSPS" },
  { name: "SHASTIK SHALI PINDA SWEDAN_IPD", shortName: "SHASTIK SHALI PINDA SWEDAN" },
  { name: "SHET DHARA", shortName: "SD" },
  { name: "SHIRO_ ABHYANG", shortName: "SHABY" },
  { name: "SHIRODHARA", shortName: "SD" },
  { name: "SHIRODHARA (BY KWATH)", shortName: "SD-KW" },
  { name: "SHIRODHARA (BY OIL)", shortName: "SD-OIL" },
  { name: "SHIRODHARA (PUSHPAKATHA)", shortName: "SHIRODHARA (KWATH)" },
  { name: "SHIRODHARA (KWATH)", shortName: "SHIRODHARA (TEL)" },
  { name: "SHIRODHARA(TEL)", shortName: "SD-Mkw" },
  { name: "SHIRODHARA WITH MEDHA KWATH", shortName: "SD-MLK" },
  { name: "SHIRODHARA WITH MILK", shortName: "SD-TAKR" },
  { name: "SHIRODHARA WITH TAKRA", shortName: "SHIRO PICHU" },
  { name: "SHIROPICHU", shortName: "SP" },
  { name: "SHIVA", shortName: "MAR-NSM" },
  { name: "SHODHANA / MARSHA NASYAM", shortName: "NB-SHWAS" },
  { name: "SHWASARI BASTI", shortName: "SNEHA PANA (PIZHICHIL)" },
  { name: "SNEHA PANA (PIZHICHIL)", shortName: "SNEHPAN" },
  { name: "SNEHPAN", shortName: "SS" },
  { name: "STHANIK SWEDAN", shortName: "STIPS" },
  { name: "STHANIK JAMBIRA PIND SWEDAN", shortName: "STPPS" },
  { name: "STHANIK PATRA PIND SWEDAN", shortName: "ST-MUD LEPA" },
  { name: "STHANIK MUD LEPA", shortName: "RBS" },
  { name: "STHANIK RUKSH BALUKA SWEDAN", shortName: "ST SSPS" },
  { name: "STHANIK SASTIK SALI PIND SWEDAN", shortName: "ST-MUD LEPA" },
  { name: "STHANIK_MUD_LEPA", shortName: "NB-SUD" },
  { name: "SUDARSHAN BASTI", shortName: "SYNERGY MUD LEPA" },
  { name: "SYNERGY MUD LEPA", shortName: "NB-TAKRA" },
  { name: "TAKRA BASTI", shortName: "TAKRA DHARA" },
  { name: "TAKRA DHARA", shortName: "TAKRA PICHIL" },
  { name: "TAKRA PICHIL", shortName: "TLM" },
  { name: "TALAM", shortName: "NB-THYRO" },
  { name: "THYROGRI BASTI", shortName: "NB-TRI" },
  { name: "TRIGAN BASTI", shortName: "UDG" },
  { name: "UDHARGASHAR", shortName: "UDW" },
  { name: "UDWARTAN", shortName: "NB-UTTAR" },
  { name: "UTTAR BASTI_IPD", shortName: "VAM" },
  { name: "VAMAN", shortName: "NB-VAUV" },
  { name: "VASU BASTI", shortName: "YPr" },
  { name: "YONIPRAKSHALAN_IPD", shortName: "YG-BILWADI (GUG+GH)" },
  { name: "IPD_BILWADI GHRUTANA (GUGGAL+GHEE)", shortName: "YG-CHARM (GUG+GH)" },
  { name: "IPD_CHARMAGRIT (GUGGAL+GHEE)", shortName: "YG-CYSTO (GUG+GH)" },
  { name: "IPD_CYSTOGRIT(GUGGAL+KAPOOR)", shortName: "YG-DIVYA (GUG+GH)" },
  { name: "IPD_DIVYASHITI (GUGGAL+GHEE)", shortName: "YG-GOKHRU-SARV (GUG+GH)" },
  { name: "IPD_GOKHRU KWATH+SARVAKALP KWATH (GUGGAL+GHEE)", shortName: "YG-KANC (GUG+GH)" },
  { name: "IPD_KANCHNAR (GUGGAL+GHEE)", shortName: "YG-KARK (GUG+GH)" },
  { name: "IPD_KARKATSHITI (GUGGAL+GHEE)", shortName: "YG-KAYA (GUG+GH)" },
  { name: "IPD_KAYAKALP KWATH (GUGGAL+GHEE)", shortName: "YG_KET (GUG+GH)" },
  { name: "IPD_KETHI (GUGGAL+GHEE)", shortName: "YG_MEDHA (GUG+GH)" },
  { name: "IPD_MEDHAGRIT (GUGGAL+GHEE)", shortName: "YG-ORTHO (GUG+GH)" },
  { name: "IPD_ORTHOGRT(GUGGAL+GHEE)", shortName: "IPD-PRANSE (GUG+GHRIT)" },
  { name: "IPD_PRANSHHITI (GUGGAL+GHRIT)", shortName: "IPD_PRNABHDHSITI(GUGGAL+GHEE+DRYESHTI)" },
  { name: "IPD_PRNABHDHSITI(GUGGAL+GHEE+DRYESHTI)", shortName: "YG-SAN (GUG+GH)" },
  { name: "IPD_SANTATI_GHRIT(GUGGAL+GHEE)", shortName: "YG-SARV (GUG+GH)" },
  { name: "IPD_SARVKALP KWATH(GUGGAL+GHEE)", shortName: "YG-VAT (GUG+TIL)" },
  { name: "IPD_VATSHITI (GUGGAL+TIL TAILA)", shortName: "YG-VAT (GUG+TIL)" }
];

